services:

  postgres:
    image: postgres:16

    container_name: postgres-db

    environment:
      POSTGRES_DB: db_url_shortener
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678x@X

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_url_shortener"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.4-alpine

    container_name: redis-cache

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    command: ["redis-server", "--appendonly", "yes"]

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 1s
      retries: 3

volumes:
  postgres-data:
  redis-data:

