server:
  port: 10689

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_url_shortener
    username: admin
    password: 12345678x@X

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health


app:
  base-url: http://short.ly