server:
  port: 10689

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_url_shortener
    username: admin
    password: 12345678x@X

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics


app:
  base-url: http://localhost:10689
  cache:
    redirect-ttl: 30m

logging:
  file:
    name: ./logs/url-shortener.log
